### ISSUE TITLE
Stopping execution with CTRL+C does not stop the execution effectively

### ISSUE THREAD

**Issue by grzesir** [Lumiwealth/lumibot#17]
This is what happens after I press CTRL+C:

```
^C2021-01-05 14:12:30,767: INFO: Strategy IntradayMomentum: Executing the on_abrupt_closing lifecycle method
2021-01-05 14:12:30,767: WARNING: Strategy IntradayMomentum: sell all
2021-01-05 14:12:30,826: INFO: market order of | 218 GLD sell | with status accepted was sent to broker 
Traceback (most recent call last):
  File "/Users/robertgrzesik/Development/alpaca-bots/traders/trader.py", line 87, in run_all
    for task in as_completed(tasks):
  File "/Users/robertgrzesik/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 244, in as_completed
    waiter.event.wait(wait_timeout)
  File "/Users/robertgrzesik/opt/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/robertgrzesik/opt/anaconda3/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/Users/robertgrzesik/Development/alpaca-bots/traders/trader.py", line 58, in _abrupt_closing
    strategy.on_abrupt_closing()
  File "/Users/robertgrzesik/Development/alpaca-bots/tools/decorators.py", line 83, in output_func
    action()
  File "/Users/robertgrzesik/Development/alpaca-bots/strategies/strategy.py", line 187, in _dump_stats
    cagr_value = cagr(df_)
  File "/Users/robertgrzesik/Development/alpaca-bots/tools/indicators.py", line 33, in cagr
    CAGR = (total_ret) ** (1 / period_years) - 1
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 79, in <module>
    trader.run_all()
  File "/Users/robertgrzesik/Development/alpaca-bots/traders/trader.py", line 88, in run_all
    results.append(task.result())
  File "/Users/robertgrzesik/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 636, in __exit__
    self.shutdown(wait=True)
  File "/Users/robertgrzesik/opt/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 236, in shutdown
    t.join()
  File "/Users/robertgrzesik/opt/anaconda3/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/Users/robertgrzesik/opt/anaconda3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/Users/robertgrzesik/Development/alpaca-bots/traders/trader.py", line 58, in _abrupt_closing
    strategy.on_abrupt_closing()
  File "/Users/robertgrzesik/Development/alpaca-bots/tools/decorators.py", line 83, in output_func
    action()
  File "/Users/robertgrzesik/Development/alpaca-bots/strategies/strategy.py", line 185, in _dump_stats
    df_ = df_day_deduplicate(self.stats_df)
  File "/Users/robertgrzesik/Development/alpaca-bots/tools/helpers.py", line 32, in df_day_deduplicate
    if position + 1 == n_rows:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2021-01-05 14:12:30,866: INFO: New market order of | 218 GLD sell | with status accepted was submited.
2021-01-05 14:12:30,932: INFO: New transaction: sell 151 of GLD at 182.98$ per share
2021-01-05 14:12:30,932: INFO: market order of | 218 GLD sell | with status new was partially filled
^C2021-01-05 14:12:30,966: INFO: Strategy IntradayMomentum: Executing the on_abrupt_closing lifecycle method
2021-01-05 14:12:30,967: WARNING: Strategy IntradayMomentum: sell all
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/robertgrzesik/Development/alpaca-bots/brokers/broker.py", line 332, in cancel_orders
    tasks.append(executor.submit(self.cancel_order, order))
  File "/Users/robertgrzesik/opt/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 181, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
(base) Roberts-MBP:alpaca-bots robertgrzesik$ 
```

**Comment by SlimBeji** [comment]
`CAGR = (total_ret) ** (1 / period_years) - 1`

period_years can be equals to 0 which leads to a division by Zero.

**Comment by grzesir** [comment]
maybe we should just do a try/catch around this or put it in an if statement that checks period_years?

**Comment by SlimBeji** [comment]
release 0.0.7 solves the bug
