### ISSUE TITLE
exchange_id for alpaca? 

### ISSUE THREAD

**Issue by patrickchirdon** [Lumiwealth/lumibot#280]
Recently I alpaca was not working when I tried to run the crypto_custom_etf.py strategy.... It simply doesn't run anymore.  I get an error about the exchange_id which there does not appear to be one for alpaca.... I know Alpaca recently made some server changes.... Any idea what the issue is?

**Comment by patrickchirdon** [comment]
crypto_custom_etf.py
Traceback (most recent call last):
  File "/home/patrick/anaconda3/envs/lumibot-env/lib/python3.8/site-packages/lumibot/data_sources/ccxt_data.py", line 41, in __init__
    exchange_class = getattr(ccxt, api_keys["exchange_id"])
KeyError: 'exchange_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "crypto_custom_etf.py", line 141, in <module>
    broker = Ccxt(ALPACA_CONFIG)
  File "/home/patrick/anaconda3/envs/lumibot-env/lib/python3.8/site-packages/lumibot/brokers/ccxt.py", line 21, in __init__
    CcxtData.__init__(self, config, max_workers=max_workers, chunk_size=chunk_size)
  File "/home/patrick/anaconda3/envs/lumibot-env/lib/python3.8/site-packages/lumibot/data_sources/ccxt_data.py", line 45, in __init__
    api_keys["exchange_id"]
KeyError: 'exchange_id'
