### ISSUE TITLE
Not possible to get historical_prices in minutes while backtesting

### ISSUE THREAD

**Issue by artur-kalteis** [Lumiwealth/lumibot#378]
I am using the simple example from the documentation

# Get the data for AAPL for the last 30 minutes
bars =  self.get_historical_prices("AAPL", 30, "minute")

It starts to work again if i change from "minute" to "day".

Error Log:

 File "C:\Privat\Skynet\Skynet\Lumibot_example.py", line 51, in on_trading_iteration
    bars =  self.get_historical_prices(symbol, 30, "minute")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Privat\Skynet\Python_ENV\skynet_env\Lib\site-packages\lumibot\strategies\strategy.py", line 2869, in get_historical_prices
    return self.broker.data_source.get_historical_prices(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Privat\Skynet\Python_ENV\skynet_env\Lib\site-packages\lumibot\data_sources\yahoo_data.py", line 175, in get_historical_prices
    response = self._pull_source_symbol_bars(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Privat\Skynet\Python_ENV\skynet_env\Lib\site-packages\lumibot\data_sources\yahoo_data.py", line 67, in _pull_source_symbol_bars
    self._parse_source_timestep(timestep, reverse=True)
  File "C:\Privat\Skynet\Python_ENV\skynet_env\Lib\site-packages\lumibot\data_sources\data_source.py", line 275, in _parse_source_timestep
    raise UnavailabeTimestep(self.SOURCE, timestep)
lumibot.data_sources.exceptions.UnavailabeTimestep: **YAHOO data source does not have data with 'minute' timestep**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Privat\Skynet\Python_ENV\skynet_env\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 869, in run
    raise RuntimeError("Exception encountered, stopping BackTest.") from e
RuntimeError: Exception encountered, stopping BackTest.

**Comment by grzesir** [comment]
Where exactly in the docs is this? The error message is correct, yahoo does
not have minute data and you would either have to use polygon/pandas for
minute data, or switch it to using day data.

Please let me know where you got this code and I can update the docs

Robert Grzesik 347-635-3416

**Comment by artur-kalteis** [comment]
A Information would be helpfull, that this is only possible with polygon/pandas..

![image](https://github.com/Lumiwealth/lumibot/assets/44962900/baf9b1f9-3862-440a-b998-48be853d894d)


https://lumibot.lumiwealth.com/strategy_methods.data/lumibot.strategies.strategy.Strategy.get_historical_prices.html#self-get-historical-prices
