### ISSUE TITLE
Error when attempting `pip install lumibot`

### ISSUE THREAD

**Issue by itsmostafa** [Lumiwealth/lumibot#383]
Getting the following error when attempting to run `pip install lumibot` on Python 3.12.2:

`../../meson.build:2:0: ERROR: Unable to detect linker for compiler cc -Wl,--version`

This error is coming from the Pandas package:

```
      Build type: native build
      Project name: pandas
      Project version: 2.1.0
```

I'm running on: 

```
MacOS: Sonoma 14.2.1
Chip: M1 Pro
```

**Comment by grzesir** [comment]
Can you please provide more of the error?

Robert Grzesik 347-635-3416

**Comment by itsmostafa** [comment]
Here you go:

```bash
2024-02-29T14:40:34,639   Build type: native build
2024-02-29T14:40:34,639   Project name: pandas
2024-02-29T14:40:34,639   Project version: 2.1.0

2024-02-29T14:40:34,639   ../../meson.build:2:0: ERROR: Unable to detect linker for compiler `cc -Wl,--version`
2024-02-29T14:40:34,639   stdout:
2024-02-29T14:40:34,639   stderr: ld: unknown options: --version
2024-02-29T14:40:34,639   clang: error: linker command failed with exit code 1 (use -v to see invocation)


2024-02-29T14:40:34,639   A full log can be found at /private/var/folders/bv/88bccsg94r53lwmjkvy69_780000gn/T/pip-install-ettb173f/pandas_5865ca32866549e3868797d37211f1aa/.mesonpy-i7laa44k/build/meson-logs/meson-log.txt
2024-02-29T14:40:34,668   ERROR: Preparing metadata (pyproject.toml) exited with 1
2024-02-29T14:40:34,671   [bold magenta]full command[/]: [blue]/Users/********/Projects/purealgo/purealgo-metrics/.venv/bin/python3.12 /Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/bv/88bccsg94r53lwmjkvy69_780000gn/T/tmpc8kv6173[/]
2024-02-29T14:40:34,671   [bold magenta]cwd[/]: /private/var/folders/bv/88bccsg94r53lwmjkvy69_780000gn/T/pip-install-ettb173f/pandas_5865ca32866549e3868797d37211f1aa
2024-02-29T14:40:34,671 ERROR: metadata generation failed
2024-02-29T14:40:34,672 Exception information:
2024-02-29T14:40:34,672 Traceback (most recent call last):
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
2024-02-29T14:40:34,672     distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
2024-02-29T14:40:34,672                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 766, in prepare_metadata_for_build_wheel
2024-02-29T14:40:34,672     return super().prepare_metadata_for_build_wheel(
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
2024-02-29T14:40:34,672     return self._call_hook('prepare_metadata_for_build_wheel', {
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
2024-02-29T14:40:34,672     self._subprocess_runner(
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
2024-02-29T14:40:34,672     call_subprocess(
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
2024-02-29T14:40:34,672     raise error
2024-02-29T14:40:34,672 pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1
2024-02-29T14:40:34,672 
2024-02-29T14:40:34,672 The above exception was the direct cause of the following exception:
2024-02-29T14:40:34,672 
2024-02-29T14:40:34,672 Traceback (most recent call last):
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
2024-02-29T14:40:34,672     status = run_func(*args)
2024-02-29T14:40:34,672              ^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
2024-02-29T14:40:34,672     return func(self, options, args)
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
2024-02-29T14:40:34,672     requirement_set = resolver.resolve(
2024-02-29T14:40:34,672                       ^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
2024-02-29T14:40:34,672     result = self._result = resolver.resolve(
2024-02-29T14:40:34,672                             ^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
2024-02-29T14:40:34,672     state = resolution.resolve(requirements, max_rounds=max_rounds)
2024-02-29T14:40:34,672             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
2024-02-29T14:40:34,672     failure_causes = self._attempt_to_pin_criterion(name)
2024-02-29T14:40:34,672                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
2024-02-29T14:40:34,672     criteria = self._get_updated_criteria(candidate)
2024-02-29T14:40:34,672                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
2024-02-29T14:40:34,672     self._add_to_criteria(criteria, requirement, parent=candidate)
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
2024-02-29T14:40:34,672     if not criterion.candidates:
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
2024-02-29T14:40:34,672     return bool(self._sequence)
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
2024-02-29T14:40:34,672     return any(self)
2024-02-29T14:40:34,672            ^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
2024-02-29T14:40:34,672     return (c for c in iterator if id(c) not in self._incompatible_ids)
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
2024-02-29T14:40:34,672     candidate = func()
2024-02-29T14:40:34,672                 ^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
2024-02-29T14:40:34,672     base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
2024-02-29T14:40:34,672                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
2024-02-29T14:40:34,672     self._link_candidate_cache[link] = LinkCandidate(
2024-02-29T14:40:34,672                                        ^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
2024-02-29T14:40:34,672     super().__init__(
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
2024-02-29T14:40:34,672     self.dist = self._prepare()
2024-02-29T14:40:34,672                 ^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
2024-02-29T14:40:34,672     dist = self._prepare_distribution()
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
2024-02-29T14:40:34,672     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
2024-02-29T14:40:34,672     return self._prepare_linked_requirement(req, parallel_builds)
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
2024-02-29T14:40:34,672     dist = _get_prepared_distribution(
2024-02-29T14:40:34,672            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
2024-02-29T14:40:34,672     abstract_dist.prepare_distribution_metadata(
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
2024-02-29T14:40:34,672     self.req.prepare_metadata()
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 579, in prepare_metadata
2024-02-29T14:40:34,672     self.metadata_directory = generate_metadata(
2024-02-29T14:40:34,672                               ^^^^^^^^^^^^^^^^^^
2024-02-29T14:40:34,672   File "/Users/********/Projects/purealgo/purealgo-metrics/.venv/lib/python3.12/site-packages/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
2024-02-29T14:40:34,672     raise MetadataGenerationFailed(package_details=details) from error
2024-02-29T14:40:34,672 pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
2024-02-29T14:40:34,681 Remote version of pip: 24.0
2024-02-29T14:40:34,681 Local version of pip:  24.0
2024-02-29T14:40:34,682 Was pip installed by pip? True
2024-02-29T14:40:34,682 Removed pandas<=2.1.0,>=2.0.0 from https://files.pythonhosted.org/packages/6f/31/a4a8e7367856d9584d0332793edfe631182a9cca885f12dbe2dd77c10c4a/pandas-2.1.0.tar.gz (from lumibot) from build tracker '/private/var/folders/bv/88bccsg94r53lwmjkvy69_780000gn/T/pip-build-tracker-_c9pdgee'
2024-02-29T14:40:34,682 Removed build tracker: '/private/var/folders/bv/88bccsg94r53lwmjkvy69_780000gn/T/pip-build-tracker-_c9pdgee'

```

**Comment by itsmostafa** [comment]
FYI, I can successfully install `pandas==2.2.1` but for some reason when install `lumibot`, its seems to be attempting to install pandas version 2.1.0.

**Comment by grzesir** [comment]
This error mentions something called purealgo-metrics. I don’t believe that
part of lumibot, I think that’s something specific to your computer.

Also (and more importantly), you’re using Python 3.12. We don’t support
that version of Python yet, there are a lot of packages that still haven’t
been upgraded to work with it. Try Python 3.11

Robert Grzesik 347-635-3416

**Comment by itsmostafa** [comment]
You're right. It works on Python 3.11. Thank you for quickly getting back to me. Closing issue...

**Comment by grzesir** [comment]
No problem. Let me know how it goes. There’s a bunch of example projects in
this github repo and you can find more here (with backtests):
https://github.com/Lumiwealth-Strategies

If you want to get access to our premium algorithms or you want to take our
courses on lumibot then you can subscribe to one of our plans at
lumiwealth.com

Robert Grzesik 347-635-3416
