### ISSUE TITLE
 metadata-generation-failed

### ISSUE THREAD

**Issue by miracle0403** [Lumiwealth/lumibot#407]
I keep seeing this error each time I want to install Lumibot via Pip

 A full log can be found at C:\Users\MIRACLE\AppData\Local\Temp\pip-install-86fsa512\pandas_f1bce164266c41d6b460452e3b2c646a\.mesonpy-q6dm
w3b6\build\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by grzesir** [comment]
What version of Python are you running? We do not support v12

Robert Grzesik 347-635-3416

**Comment by frmatt** [comment]
im using Python 3.12.2 and get the same error, what can i do?

**Comment by jimwhite** [comment]
> im using Python 3.12.2 and get the same error, what can i do?

Downgrade to 3.11.

**Comment by vavra7** [comment]
I was gradually downgrading python version to 3.7 and pip version to 22.3. Nothing helps. Lumibot is not possible to install.

```
Collecting ibapi==9.81.1.post1
  Using cached ibapi-9.81.1.post1.tar.gz (61 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-krpzyef_/ibapi_c51969747c234e62a860941985cec57d/setup.py", line 5, in <module>
          from src.ibapi import get_version_string
      ModuleNotFoundError: No module named 'src.ibapi'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
```
